### ISSUE TITLE
Running Colorization

### ISSUE THREAD

**Issue by gongbang02** [ohayonguy/PMRF#19]
Hi, thank you for this amazing project! I'm just wondering if I want to do colorization task, which code should I run? Is running test.sh directly on my data (black and white images) the correct way?

**Comment by ohayonguy** [comment]
> I have the same question here, I am wondering if it's normal to take hours to run colorization for the checkpoint in:
> 
> ```
> ├── controlled_experiments/     # Checkpoints for the controlled experiments
> │   ├── colorization_gaussian_noise_025/
> │   │   ├── pmrf/
> │   │   │   └── epoch=999-step=273000.ckpt
> ```
> 
> with code:
> 
> ```
> for method in  "pmrf"; do
> python test.py \
> --precision "32" \
> --degradation "colorization_gaussian_noise_025" \
> --test_data_root "/path/to/celebahq_test_256" \
> --num_gpus 1 \
> --batch_size 128 \
> --num_workers 10 \
> --img_size 256 \
> --ckpt_path "./checkpoints/controlled_experiments/colorization_gaussian_noise_025/${method}/epoch=999-step=273000.ckpt" \
> --results_path "./controlled_experiments_results/" \
> --num_flow_steps 100
> #--num_flow_steps 5 10 20 50 100
> ```

Hi @luchaoqi :) It's definitely not normal for the code to run for hours. Are you using a GPU? Can you provide some more details on your setup so we could investigate this?
Thanks!

**Comment by gongbang02** [comment]
Hi @ohayonguy ! I'm testing on a greyscale image like this
![image](https://github.com/user-attachments/assets/19d1a1be-9626-492b-805e-ab3e4f75b055)
I ran the following script:
for method in  "pmrf"; do
python test.py \
--precision "32" \
--degradation "colorization_gaussian_noise_025" \
--test_data_root "/path/to/celebahq_test_256" \
--num_gpus 1 \
--batch_size 128 \
--num_workers 10 \
--img_size 256 \
--ckpt_path "./checkpoints/controlled_experiments/colorization_gaussian_noise_025/${method}/epoch=999-step=273000.ckpt" \
--results_path "./controlled_experiments_results/" \
--num_flow_steps 100
In the generated /colorization_gaussian_noise_025/pmrf/num_flow_steps=100/xhat/ folder, the output image looks like this:
![image](https://github.com/user-attachments/assets/86a00618-3413-4cc1-b7bb-39c33c917400)
Do you have any clue what could be wrong with how I'm running the code?

**Comment by ohayonguy** [comment]
Hi @gongbang02 
Please note that our code for colorization is not designed to handle given grayscale images. The code is expected to receive colored images. It then converts them to grayscale, adds noise, and then it denoises and colorizes the result. This design is meant for demonstration purposes, so that people may assess the algorithm on different data sets of clean, colored images (e.g., by measuring PSNR), and easily compare the performance with other methods.

To run the method for non-noisy grayscale images, you have to train the algorithm on such images (because our checkpoint also assumes noise). Moreover, you need to slightly alter the code to be able to receive degraded images instead of clean ones.

Finally, please note that this is different for the blind image restoration method (inference.py), where it expects to receive degraded images instead of clean ones.

I hope this helps.
