### ISSUE TITLE
unable to install Natten.

### ISSUE THREAD

**Issue by zachysaur** [ohayonguy/PMRF#6]
tried everything unable to install Natten

**Comment by ohayonguy** [comment]
@zachysaur Are you trying that with windows or linux ?

**Comment by zachysaur** [comment]
windows

**Comment by ohayonguy** [comment]
Please refer to https://github.com/ohayonguy/PMRF/issues/4
I hope you'll be able to solve this. If you do, please share your solution :)

**Comment by zachysaur** [comment]
ok i will try thank you

**Comment by ohayonguy** [comment]
@zachysaur I am sorry for the inconvenience. I just added the following note to our installation instructions:

**Note for Windows users:** *It appears that several Windows users have been unable to install the `natten` package, which is required in order to use the HDiT model architecture in PMRF. If you also face this issue, you may train PMRF using a different architecture, such as UNet, and avoid using the `natten` package. If you managed to install `natten` on Windows, please share your solution as this may benefit other users 😊 Thank you!*
