### ISSUE TITLE
windows for natten

### ISSUE THREAD

**Issue by sdbds** [ohayonguy/PMRF#8]
Someone made these.

https://github.com/2kpr/ComfyUI-PMRF

https://huggingface.co/2kpr/NATTEN-Windows

**Comment by WalkingwithAI** [comment]
> Someone made these. 有人制作了这些。
> 
> https://github.com/2kpr/ComfyUI-PMRF
> 
> https://huggingface.co/2kpr/NATTEN-Windows

I love you my friend.

**Comment by ohayonguy** [comment]
Great! Thanks! Will add to the readme.

**Comment by passionlu** [comment]
Thank you! The Gradio demo has been successfully deployed and running in Windows 11.

**Comment by cyberbol** [comment]
I am a noob, but I managed to install it. Can we also colourize picture ?

**Comment by ohayonguy** [comment]
@cyberbol If you refer to our blind face image restoration model, then unfortunately no. We did not train our model for image colorization, but such an extension should be straightforward! Note that we do conduct colorization experiments in section 5.2, but for a specific type of color degradation and noise.

If you decide to extend our model for blind image colorization, please share your results! Thanks :)

**Comment by WalkingwithAI** [comment]
> Thank you! The Gradio demo has been successfully deployed and running in Windows 11.

Hello my friend, I deployed it in windows11 according to the hugggingface Gradio demo, but occured this error. It might be due to an incorrect version of torchvision being used. May I ask which versions of torch and torchvision you are using? Thank you for your response!

Error Message：
Traceback (most recent call last):
  File "G:\AI\PMRF\app.py", line 17, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "D:\Miniconda\envs\pmrf\lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "D:\Miniconda\envs\pmrf\lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "D:\Miniconda\envs\pmrf\lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "D:\Miniconda\envs\pmrf\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Miniconda\envs\pmrf\lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "D:\Miniconda\envs\pmrf\lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

**Comment by ohayonguy** [comment]
@WalkingwithAI Please read https://github.com/ohayonguy/PMRF?tab=readme-ov-file#%EF%B8%8F-installation

**Comment by WalkingwithAI** [comment]
> @WalkingwithAI Please read https://github.com/ohayonguy/PMRF?tab=readme-ov-file#%EF%B8%8F-installation

Thank you my friend, it worked.
